In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Part-1 (codebasics)

In [2]:
train = pd.read_csv('train.csv')
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
train = train.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis='columns')
train

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [6]:
target = train.Survived
inputs = train.drop('Survived', axis='columns')

In [7]:
print(target.head(), '\n\n', inputs.head())

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64 

    Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500


In [8]:
dummies = pd.get_dummies(inputs.Sex)
dummies

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [9]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [10]:
inputs.drop('Sex', axis='columns', inplace=True)
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [11]:
inputs[:10]

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1
5       3   NaN   8.4583       0     1
6       1  54.0  51.8625       0     1
7       3   2.0  21.0750       0     1
8       3  27.0  11.1333       1     0
9       2  14.0  30.0708       1     0

In [12]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1
6       1  54.000000  51.8625       0     1
7       3   2.000000  21.0750       0     1
8       3  27.000000  11.1333       1     0
9       2  14.000000  30.0708       1     0

In [13]:
from sklearn.model_selection import train_test_split as tts


In [14]:
xtrain, xtest, ytrain, ytest = tts(inputs, target, test_size=0.2)

In [15]:
print(len(xtrain), '\n', len(xtest), '\n',len(inputs))

712 
 179 
 891


In [16]:
from sklearn.naive_bayes import GaussianNB as gss

In [17]:
model = gss()

In [18]:
model.fit(xtrain, ytrain)

GaussianNB()

In [19]:
model.score(xtest, ytest)

0.7988826815642458

In [20]:
model.score(xtrain, ytrain)

0.776685393258427

In [21]:
xtest[:10]

Pclass        Age      Fare  female  male
482       3  50.000000    8.0500       0     1
773       3  29.699118    7.2250       0     1
561       3  40.000000    7.8958       0     1
618       2   4.000000   39.0000       1     0
678       3  43.000000   46.9000       1     0
575       3  19.000000   14.5000       0     1
519       3  32.000000    7.8958       0     1
792       3  29.699118   69.5500       1     0
727       3  29.699118    7.7375       1     0
319       1  40.000000  134.5000       1     0

In [22]:
ytest[:10]

482    0
773    0
561    0
618    1
678    0
575    0
519    0
792    0
727    1
319    1
Name: Survived, dtype: int64

In [23]:
model.predict(xtest[:10])

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [24]:
model.predict_proba(xtest[:10])

array([[9.88215918e-01, 1.17840818e-02],
       [9.88414044e-01, 1.15859556e-02],
       [9.88942427e-01, 1.10575732e-02],
       [1.21272021e-02, 9.87872798e-01],
       [4.26891536e-02, 9.57310846e-01],
       [9.86496827e-01, 1.35031735e-02],
       [9.88666629e-01, 1.13333715e-02],
       [2.16213809e-02, 9.78378619e-01],
       [5.80647319e-02, 9.41935268e-01],
       [7.02568115e-05, 9.99929743e-01]])

# Part-2 (codebasics)

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [26]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [27]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [28]:
df.shape

(5572, 2)

In [29]:
df['spam'] = df.Category.apply(lambda x : 1 if x == 'spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [30]:
xtrain.values

array([[ 1.    , 63.    , 77.9583,  1.    ,  0.    ],
       [ 2.    , 25.    , 41.5792,  0.    ,  1.    ],
       [ 3.    , 30.    ,  7.8958,  0.    ,  1.    ],
       ...,
       [ 2.    ,  0.83  , 18.75  ,  0.    ,  1.    ],
       [ 3.    , 21.    ,  8.6625,  0.    ,  1.    ],
       [ 1.    , 62.    , 26.55  ,  0.    ,  1.    ]])

In [31]:
xtrain, xtest, ytrain, ytest = tts(df.Message, df.spam, test_size=0.25)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
xtrain_count = v.fit_transform(xtrain.values)
xtrain_count.toarray()[:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
from sklearn.naive_bayes import MultinomialNB as mtb

model = mtb()
model.fit(xtrain_count, ytrain)

MultinomialNB()

In [34]:
email =  [
    'Hello buddy, lets go for a lunch',
    'click wwww.xxsdatingapp.com to date in ur area',
    'fuck you xxx, call our model representative ',
    "Hey Fahad, what's up"
]
emails_count = v.transform(email)
model.predict(emails_count)

array([0, 1, 1, 0], dtype=int64)

In [35]:
xtest_count = v.transform(xtest)
model.score(xtest_count, ytest)

0.9842067480258435

In [36]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', mtb())
])

In [37]:
clf.fit(xtrain, ytrain)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [38]:
clf.score(xtest, ytest)

0.9842067480258435